added 0x10-https_ssl

diff --git a/0x10-https_ssl/0-world_wide_web b/0x10-https_ssl/0-world_wide_web
--- a/0x10-https_ssl/0-world_wide_web
+++ b/0x10-https_ssl/0-world_wide_web
@@ -1,16 +1,56 @@
-#!/usr/bin/env bash
-# prints domains and subdomains
+#!/bin/bash
 
-print_domain_subdomain () {
-    dig "$1" | grep -A1 'ANSWER SECTION:' | sed -r "s/$1./$2/g" | awk -F" " ' NR==2 { print "The subdomain " $1 " is a " $4 " record and points to " $5 }'
+get_record_info() {
+    local domain="$1"
+    local subdomain="$2"
+    local record_type
+    local destination
+
+    if [[ -z "$subdomain" ]]; then
+        case "$domain" in
+            "www" )
+                record_type="A"
+                destination="$(dig +short A www.$domain)"
+                ;;
+            "lb-01" )
+                record_type="A"
+                destination="$(dig +short A lb-01.$domain)"
+                ;;
+            "web-01" )
+                record_type="A"
+                destination="$(dig +short A web-01.$domain)"
+                ;;
+            "web-02" )
+                record_type="A"
+                destination="$(dig +short A web-02.$domain)"
+                ;;
+            * )
+                echo "Invalid subdomain: $subdomain"
+                exit 1
+                ;;
+        esac
+    else
+        record_type="A"
+        destination="$(dig +short A $subdomain.$domain)"
+    fi
+
+    echo "The subdomain $subdomain is a $record_type record and points to $destination"
 }
 
-if [ "$#" -eq 2 ]
-then
-    print_domain_subdomain "$2.$1" "$2"
+# Parse command-line arguments
+if [[ $# -eq 0 ]]; then
+    echo "Usage: $0 domain [subdomain]"
+    exit 1
+elif [[ $# -eq 1 ]]; then
+    domain="$1"
+    subdomains=("www" "lb-01" "web-01" "web-02")
 else
-    print_domain_subdomain "www.$1" "www"
-    print_domain_subdomain "lb-01.$1" "lb-01"
-    print_domain_subdomain "web-01.$1" "web-01"
-    print_domain_subdomain "web-02.$1" "web-02"
+    domain="$1"
+    subdomain="$2"
+    subdomains=("$subdomain")
 fi
+
+# Iterate over subdomains and display information
+for subdomain in "${subdomains[@]}"; do
+    get_record_info "$domain" "$subdomain"
+done
